Repository containership/cluster-manager, pull requests merged in 2019-08, with the labels that each got.

#86 Correctly set Kind of the owner reference
  pkg/coordinator/authorization_role_binding_controller.go
Labels: type/bug

#91 Don't deploy for default make invocation
  Makefile
Labels: type/maintenance

#94 Update go version to 1.12.9
  Dockerfile.agent
  Dockerfile.coordinator
Labels: component/security, type/maintenance

#99 Fix coordinate lookup file provider index keys for aws and gce
  pkg/geohash/coordinates_lookup.go
  pkg/geohash/geohash_test.go
Labels: type/bug
